### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by za970120604** [megvii-research/AAAI2023-PVD#1]
Hello , first thanks for your great team work ! I wonder if it supports custom dataset in form of colmap or other format . Also I see that your team plans to release some guide in [AAAI2023-PVD](https://github.com/megvii-research/AAAI2023-PVD)/[tools](https://github.com/megvii-research/AAAI2023-PVD/tree/main/tools)/details.md , is it on the fly ?

**Comment by Fangkang515** [comment]
Yes, our dataset format is based on the [torch-ngp](https://github.com/ashawkey/torch-ngp/tree/3b066b6cd6ccd3610cb66a56a54f5daaf12a8033), which totally supports custom dataset in form of colmap. 
The specific steps for supporting custom dataset are as follows:

- 1. take a video / many photos from different views 
- 2. put the video under a path like ./data/custom/video.mp4 or the images under ./data/custom/images/*.jpg.
- 3. call the preprocess code: (should install ffmpeg and colmap first! refer to the  [colmap2nerf.py](https://github.com/ashawkey/torch-ngp/blob/3b066b6cd6ccd3610cb66a56a54f5daaf12a8033/scripts/colmap2nerf.py) for more options.)
    - python colmap2nerf.py --video ./data/custom/video.mp4 --run_colmap # if use video
    - python colmap2nerf.py --images ./data/custom/images/ --run_colmap # if use images
- 4. it should create the transform.json, and you can train with: (you'll need to try with different scale & bound & dt_gamma to make the object correctly located in the bounding box and render fluently.)


Then you can train a teacher and distill students with various structures according to our introduction：https://github.com/megvii-research/AAAI2023-PVD
