### ISSUE TITLE
about self.clip_loss()

### ISSUE THREAD

**Issue by xuxumiao777** [megvii-research/AAAI2023-PVD#5]
Hi, thanks for your excellent work, it really benefits me a lot.
I have a question about self.clip_loss() which is used in train_step() function located in file distill_mutual/utils.py. I can not find where it is defined. Could you please tell me where it is defined and how it works?

Thank you in advance. ^_^

**Comment by Fangkang515** [comment]
Thank you for your attention.

This was an oversight on my part during code cleanup. In fact, the execution condition for this piece of [code](https://github.com/megvii-research/AAAI2023-PVD/blob/PVD-AL/distill_mutual/utils.py#L1124) has always been False, i.e., self.clip_loss() is not run. Please directly delete the redundant code from lines [1123](https://github.com/megvii-research/AAAI2023-PVD/blob/PVD-AL/distill_mutual/utils.py#L1123) to [1142](https://github.com/megvii-research/AAAI2023-PVD/blob/PVD-AL/distill_mutual/utils.py#L1142), this will not affect the normal operation of the code.

If you have any other questions, feel free to contact me.

**Comment by xuxumiao777** [comment]
Oh, all clear now.
