### ISSUE TITLE
关于模型格式

### ISSUE THREAD

**Issue by LZXBIT18** [megvii-research/AAAI2023-PVD#6]
你好，请问这个算法在数据格式之间的转化都是基于模型保存文件为.pth吗

**Comment by Fangkang515** [comment]
你好，感谢关注。

如果你想把模型A转化为模型B，那么需要的文件和代码包括：
- 模型A上训好的权重文件(.pth)
- 能够inference 模型A的代码
- 模型B的网络结构

我们[方法](http://sk-fun.fun/PVD-AL/)里使用了较为复杂的蒸馏步骤，用以保证最终的student性能。

但如果你对转化后的模型性能没有极端的要求，通常你只需要用teacher模型造充足的数据，以及使用我们的active learning策略:在PSNR较低的视角附近生成更多的训练数据就足够了。如果teacher的点数较高的话，这种简单的蒸馏也能获得超越from scratch 训练的student。
